### ISSUE TITLE
Bare CREFs

### ISSUE THREAD

**Issue by yaronf** [cabo/kramdown-rfc#237]
Hi Carsten, it would be nice if we had Markdown syntax for simple CREFs, as this would generate:

```
<cref> An editorial comment that I want rendered with a yellow background. </cref>
```

As far as I can tell, only more complicated footnotes are supported.

Currently this Markdown syntax is interpreted as a "real" comment, i.e. not rendered at all:

```
[//]: A disappearing comment.
```

But since this syntax is not widely used (AFAIK), maybe it could be coopted for CREFs.

**Comment by cabo** [comment]
Hi Yaron,


> ```
> <cref> An editorial comment that I want rendered with a yellow background. </cref>
> ```

This syntax of course works (you can write XML anywhere), as does the footnote syntax:

```
[^mycref]

[^mycref]: An editorial comment that I want rendered with a yellow background. 
```

...even if a bit clumsy.

> As far as I can tell, only more complicated footnotes are supported.
> 
> Currently this Markdown syntax is interpreted as a "real" comment, i.e. not rendered at all:
> 
> ```
> [//]: A disappearing comment.
> ```

It is not a comment, but a link target.  You can use that target in a [link][//].


> But since this syntax is not widely used (AFAIK), maybe it could be coopted for CREFs.

Between the availability of the XML syntax (use `<cref markdown="1">` if you want to use markdown markup in the cref) and the footnote syntax, I didn't see a strong reason to introduce a third, non-standard syntax.

**Comment by cabo** [comment]
cref is a span-level element in RFCXML, so it doesn't quite fit block-level mechanisms.

Something like

```
{:cref}
> Here is my comment
```

would already today work out of the box (for an appropriate definition of a cref ALD), but creates a syntax error because the cref is around the t and not the other way round.

Similar problem even with the potential introduction of syntax used in pandoc markdown for warning labels or some such:

```
::: cref
Here is my comment
:::
```

(in both cases, "cref" might be replaced by a less arcane word).

So there needs to be a way to do a block-level cref, which is a cref nested into a t.

I think in the end `<cref>Here is my comment</cref>` starts to look good...

**Comment by yaronf** [comment]
Sigh. Thank you.

**Comment by cabo** [comment]
(I'm not giving up on this, I see the need for less heavy comments -- it just sometimes takes a while before the right solution comes to mind.)

**Comment by cabo** [comment]
The best I could come up with was a span GI hack that enables:

```
{:cref}
> Here is my comment
```

That will be in 1.7.18, but right now I'm not pushing new revisions to minimize risk before the upcoming I-D deadline.
So if you find this syntax better, look forward to it for after the deadline...

**Comment by yaronf** [comment]
Looks helpful. I'll give it a try with -01.
